version: 2.0
jobs:
  deploy:
    docker:
      - image: circleci/command-convenience:0.1

    working_directory: /home/circleci/elk

    steps:
      - run: docker-compose up -d

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: org-global
          filters:
            branches:
              only: master
